version: "3.8"
services:
  backend:
    container_name: nodejsv18
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - './src:/app/src'